#!/bin/bash

THISTLE=`which thistle`
PID_FILE="/var/run/thistle.pid"
CONF_FILE="/etc/thistle/config.py"

start_func(){
  if pid=`status_func` >/dev/null ;then
    echo "\`thistle' is already running: $pid"
    exit 1
  fi
  echo -n "Starting thistle: "
  nohup ${THISTLE} -c ${CONF_FILE} start >&- 2>&- <&- &
  sleep 3
  if [ `status_func` = "NG" ]; then
    echo "NG"
    exit $?
  else
    echo "OK"
    exit 0
  fi
}

stop_func(){
  if pid=`status_func` >/dev/null ;then
    echo -n "Stopping thistle: "
    ${THISTLE} ${ARGS} -c ${CONF_FILE} stop
    [ $? -ne 0 ] && echo NG || echo OK
    exit $?
  fi
  echo "Not runnning"
  exit 1
}

test_func(){
  ${THISTLE} ${ARGS} -c ${CONF_FILE} test
  exit $?
}

status_func(){
  if [ -s $PID_FILE ];then
    pid=`cat $PID_FILE`
    if [ -d /proc/$pid ];then
      echo "$pid"
      return 0
    fi
  fi
  echo "NG"
  return 1
}

CMD=$1
shift
ARGS="$*"
case "${CMD}" in
  start)
    start_func
    ;;
  stop)
    stop_func
    ;;
  test)
    test_func
    ;;
  status)
    status_func
    ;;
  *)
    ${THISTLE} -h
    exit 1
esac
